/**
 * Import User-Provided Event Data
 *
 * Imports the three spreadsheets of event data provided by the user
 * Usage: bun run scripts/import-user-data.ts [--dry-run]
 */

import { importEvents, type EventRow } from './import-events'

const dryRun = process.argv.includes('--dry-run')

// Sheet 1: MSK Hospital Events
const mskEvents: EventRow[] = [
	{
		date: 'Wednesday, Dec 11, 2024',
		location: 'MSK',
		location_detail: 'Main Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Kely Pinheiro',
		number_of_musicians: 1,
		hours: 1,
		event_type: 'Performance',
		website: 'https://www.kelypinheiro.com/',
		program_name: 'MSK',
	},
	{
		date: 'Monday, Dec 16, 2024',
		location: 'MSK',
		location_detail: 'MDP Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Gabriel Aldort',
		number_of_musicians: 1,
		hours: 1,
		event_type: 'Performance',
		website: 'https://galdortmusic.com/',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, Jan 14, 2025',
		location: 'MSK',
		location_detail: 'Main Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Yifei Xu',
		number_of_musicians: 1,
		hours: 1,
		status: 'N/A',
		instrumentation: 'solo piano, will use Mets piano',
		description: 'Award-winning pianist Yifei Xu captivates audiences with her virtuosity, lyricism, and seamless fusion of classical and avant-garde styles.',
		event_type: 'Performance',
		website: 'https://yifeixu.org/about',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, Jan 28, 2025',
		location: 'MSK',
		location_detail: 'MDP Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Trio Fadolin',
		number_of_musicians: 3,
		hours: 1,
		total_fee: 3,
		instrumentation: 'Fadolín, Cello & Violin. Will need three chairs',
		description: 'Trio Fadolín performs an eclectic repertoire from around the world and across the ages, featuring music from Eastern Europe, Scandinavia, Latin-inspired grooves, and much more, all featuring the fadolín, a unique string instrument that encompasses the range of the violin, viola, and cello.',
		event_type: 'Performance',
		website: 'https://fadolin.com/trio-fadolin/',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, Feb 11, 2025',
		location: 'MSK',
		location_detail: 'MDP Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Harold O\'Neal',
		number_of_musicians: 1,
		hours: 1,
		instrumentation: 'Piano',
		description: 'Harold O\'Neal, hailed as one of this generation\'s greatest pianists and composers, delivers an unforgettable performance, blending the brilliance of Duke Ellington, Kenny Kirkland, and Maurice Ravel.',
		event_type: 'Performance',
		website: 'https://www.pianocinema.com/',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, Feb 25, 2025',
		location: 'MSK',
		location_detail: 'MDP Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'JuanMa Morales',
		number_of_musicians: 1,
		hours: 1,
		instrumentation: 'Guitar & voice',
		description: 'Juan Manuel Morales, founder of Sonido Costeño, is a Cornell graduate and Juilliard alumnus who blends Latin, salsa, and world music into high-energy performances.',
		event_type: 'Performance',
		website: 'https://sonidocosteno.com/about/',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, Mar 11, 2025',
		location: 'MSK',
		location_detail: 'MDP Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Martha Kato',
		number_of_musicians: 1,
		hours: 1,
		status: 'CC',
		instrumentation: 'Piano',
		description: 'Born and raised in Nagoya, Japan, Martha Kato is a pianist, composer and arranger in her blossoming career in New York.',
		event_type: 'Performance',
		website: 'https://www.marthakato.com/',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, April 1, 2025',
		location: 'MSK',
		location_detail: 'MDP Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Gabi & Edu Guitar Duo',
		number_of_musicians: 2,
		hours: 1,
		total_fee: 2,
		status: 'CC',
		instrumentation: 'Guitar duo',
		description: 'Guitarists Eduardo Gutterres and Gabriele Leite bring their deep connection and love for Brazilian music to the stage.',
		event_type: 'Performance',
		website: 'https://youtu.be/r6n6RjB_TME?feature=shared',
		program_name: 'MSK',
	},
	{
		date: 'Thursday, Apr 24, 2025',
		location: 'MSK',
		location_detail: 'Saltzman Auditorium, Main Lobby',
		start_time: '12:30pm',
		end_time: '1:30pm',
		artist_name: 'Neel Murgai and Tripp Dudley - Brooklyn Raga Massive',
		number_of_musicians: 2,
		hours: 1,
		total_fee: 2,
		status: 'C',
		instrumentation: 'Sitar and Tabla duo',
		description: 'Neel Murgai (sitar) and Tripp Dudley (tabla) will be performing afternoon ragas and other delights from South Asian classical traditions and beyond.',
		event_type: 'Performance',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, Apr 29, 2025',
		location: 'MSK',
		location_detail: 'MDP Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Trio Fadolin',
		number_of_musicians: 3,
		hours: 1,
		total_fee: 3,
		status: 'CC',
		instrumentation: 'Fadolín, Cello & Violin. Will need three chairs',
		description: 'Trio Fadolín performs an eclectic repertoire from around the world and across the ages.',
		event_type: 'Performance',
		website: 'https://fadolin.com/trio-fadolin/',
		program_name: 'MSK',
	},
	{
		date: 'Wednesday, May 21, 2025',
		location: 'MSK',
		location_detail: 'Main Lobby - vending machine',
		start_time: '3:30pm',
		end_time: '4:30pm',
		artist_name: 'Rick Germanson',
		number_of_musicians: 1,
		hours: 1,
		status: 'C',
		instrumentation: 'solo piano, will use Mets piano',
		description: 'Rick Germanson has been a highly in-demand pianist on the New York City Jazz scene for well over a decade.',
		notes: 'Reception 3:30 // Speeches 4:00pm / Pianist - Ambient jazz first half hour, then little ditties as folks go up to receive awards, etc.',
		event_type: 'Performance',
		website: 'http://www.rickgermanson.com/',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, May 27, 2025',
		location: 'MSK',
		location_detail: 'MDP Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Benjamin Sutin + pianist',
		number_of_musicians: 2,
		hours: 1,
		total_fee: 2,
		status: 'C',
		instrumentation: 'violin, piano',
		notes: 'With Piano accompanist',
		event_type: 'Performance',
		website: 'https://www.bensutinmusic.com/',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, Jun 10, 2025',
		location: 'MSK',
		location_detail: 'Main Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Adam Narimatsu',
		number_of_musicians: 1,
		hours: 1,
		status: 'C',
		instrumentation: 'solo piano, will use Mets piano',
		description: 'With a mix of jazz, classical, contemporary, and an unwavering passionate energy from start to finish, Adam Narimatsu is a premiere pianist in NYC.',
		notes: 'Moved piano to internal lobby / opposite snack vendor area',
		event_type: 'Performance',
		website: 'https://www.adamnarimatsu.com/',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, Jun 24, 2025',
		location: 'MSK',
		location_detail: 'MDP Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Oren Fader',
		number_of_musicians: 1,
		hours: 1,
		status: 'C',
		instrumentation: 'solo guitar, might bring a pianist',
		description: 'Oren Fader is a versatile guitarist known for bringing classical finesse to both contemporary works and popular favorites.',
		event_type: 'Performance',
		website: 'https://orenfader.com/',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, Jul 8, 2025',
		location: 'MSK',
		location_detail: 'Main Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Adam Narimatsu',
		number_of_musicians: 1,
		hours: 1,
		instrumentation: 'Piano',
		event_type: 'Performance',
		program_name: 'MSK',
	},
	{
		date: 'Thursday, Jul 10, 2025',
		location: 'MSK',
		location_detail: 'Saltzman Auditorium, Admin Building, 5th floor (Main Hospital)',
		start_time: '7am',
		end_time: '12pm',
		artist_name: 'Larry Siegel',
		number_of_musicians: 1,
		hours: 5,
		total_fee: 5,
		status: 'C',
		instrumentation: 'Guitar',
		notes: 'Actually in the admin building opposite the Main hospital lobby entrance.',
		event_type: 'Performance',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, Jul 22, 2025',
		location: 'MSK',
		location_detail: 'MDP Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Justin Rothberg',
		number_of_musicians: 1,
		hours: 1,
		status: 'C',
		instrumentation: 'Guitar',
		description: 'Guitarist Justin Rothberg plays a blend of pop, folk, jazz standards and classical music.',
		event_type: 'Performance',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, Aug 12, 2025',
		location: 'MSK',
		location_detail: 'Main Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Adam Narimatsu',
		number_of_musicians: 1,
		hours: 1,
		status: 'C',
		instrumentation: 'solo piano, will use Mets piano',
		event_type: 'Performance',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, Aug 26, 2025',
		location: 'MSK',
		location_detail: 'MDP Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Adam Narimatsu',
		number_of_musicians: 1,
		hours: 1,
		status: 'C',
		instrumentation: 'solo piano',
		event_type: 'Performance',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, Sep 9, 2025',
		location: 'MSK',
		location_detail: 'MDP Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Harold O\'Neal',
		number_of_musicians: 1,
		hours: 1,
		status: 'CD',
		instrumentation: 'solo piano',
		description: 'Harold O\'Neal is a pianist and storyteller whose music blends the rhythmic flair of jazz with cinematic nuance.',
		event_type: 'Performance',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, Sep 16, 2025',
		location: 'MSK',
		location_detail: 'Main Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Amir Farid',
		number_of_musicians: 1,
		hours: 1,
		status: 'CD',
		instrumentation: 'solo piano',
		event_type: 'Performance',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, Oct 28, 2025',
		location: 'MSK',
		location_detail: 'MDP Lobby',
		start_time: '1pm',
		end_time: '2pm',
		artist_name: 'Ron Thompson',
		number_of_musicians: 1,
		hours: 1,
		status: 'CC',
		instrumentation: 'solo piano',
		event_type: 'Performance',
		program_name: 'MSK',
	},
	{
		date: 'Tuesday, Nov 4, 2025',
		location: 'MSK',
		location_detail: 'Main Lobby',
		start_time: '3pm',
		end_time: '5pm',
		artist_name: 'Larry Siegel',
		number_of_musicians: 1,
		hours: 2,
		total_fee: 2,
		status: 'CC',
		notes: 'Staff Appreciation Week - Beverage Station',
		event_type: 'Performance',
		program_name: 'MSK',
	},
	{
		date: 'Wednesday, Nov 5, 2025',
		location: 'MSK',
		location_detail: 'MDP Lobby (Might be Main Lobby)',
		start_time: '10am',
		end_time: '11am',
		artist_name: 'Adam Narimatsu',
		number_of_musicians: 1,
		hours: 1,
		status: 'CC',
		event_type: 'Performance',
		program_name: 'MSK',
	},
]

// Sheet 2: CLC Events
const clcEvents: EventRow[] = [
	{
		date: 'Monday, Jul 7, 2025',
		location: 'CLC',
		start_time: '2:00 PM',
		end_time: '3:00 PM',
		artist_name: 'DNA',
		event_type: 'Participatory Concert',
		status: 'CC',
		hours: 2,
		number_of_musicians: 2,
		total_fee: 487,
		notes: 'Project kick-off / pd addtl $75. to rep SFH @ kick off',
		program_name: 'CLC',
	},
	{
		date: 'Thursday, Aug 14, 2025',
		location: 'CLC',
		start_time: '2:00 PM',
		end_time: '3:00 PM',
		artist_name: 'Siegel/Bakr',
		event_type: 'Participatory Concert',
		status: 'CC',
		hours: 2,
		number_of_musicians: 2,
		total_fee: 426,
		program_name: 'CLC',
	},
	{
		date: 'Thursday, Sep 4, 2025',
		location: 'Hospice/Palliative Care Floor',
		start_time: '1:00 PM',
		end_time: '2:00 PM',
		artist_name: 'Siegel',
		event_type: 'Bedside',
		status: 'CANCELLED',
		hours: 1,
		number_of_musicians: 1,
		total_fee: 213,
		program_name: 'CLC',
	},
	{
		date: 'Thursday, Sep 4, 2025',
		location: 'CLC',
		start_time: '2:00 PM',
		end_time: '3:00 PM',
		artist_name: 'Siegel/Bakr',
		event_type: 'Participatory Concert',
		status: 'CC',
		hours: 2,
		number_of_musicians: 2,
		total_fee: 320,
		program_name: 'CLC',
	},
	{
		date: 'Thursday, Oct 9, 2025',
		location: 'CLC',
		start_time: '2:00 PM',
		end_time: '3:00 PM',
		artist_name: 'Pedro Fortunato Quartet',
		event_type: 'Participatory Concert',
		status: 'CC',
		hours: 4,
		number_of_musicians: 4,
		total_fee: 904,
		notes: 'Extra hour of prep paid',
		program_name: 'CLC',
	},
	{
		date: 'Thursday, Oct 16, 2025',
		location: 'CLC / Palliative Care / Vent Unit',
		start_time: '1:00 PM',
		end_time: '3:00 PM',
		artist_name: 'Larry Siegel',
		event_type: 'Bedside + Group Sing',
		status: 'CC',
		hours: 3,
		number_of_musicians: 2,
		total_fee: 322,
		notes: 'Bedside first hour / Group sing second hour - Siegel (2 hours)',
		program_name: 'CLC',
	},
	{
		date: 'Thursday, October 23, 2025',
		location: 'CLC',
		start_time: '2:00 PM',
		end_time: '3:00 PM',
		artist_name: 'Ligel Lambert',
		event_type: 'Visual Arts Workshop',
		status: 'H',
		hours: 1,
		number_of_musicians: 1,
		total_fee: 376,
		notes: 'Paying 2.5 hours for prep and clean up.',
		program_name: 'CLC',
	},
	{
		date: 'Thursday, Nov 6, 2025',
		location: 'CLC',
		start_time: '2:00 PM',
		end_time: '3:00 PM',
		event_type: 'Participatory Concert',
		program_name: 'CLC',
	},
	{
		date: 'Thursday, November 13, 2025',
		location: 'CLC / Palliative Care / Vent Unit',
		start_time: '1:00 PM',
		end_time: '3:00 PM',
		artist_name: 'Larry Siegal & Hasan Bakr',
		event_type: 'Bedside + Group Sing',
		status: 'CC',
		hours: 3,
		number_of_musicians: 2,
		notes: 'Bedside first hour / Group sing second hour - Siegel (2 hours) / Bakr 1 hr',
		program_name: 'CLC',
	},
	{
		date: 'Wednesday, November 19, 2025',
		location: 'CLC',
		start_time: '2:00 PM',
		end_time: '3:00 PM',
		artist_name: 'Ligel Lambert',
		event_type: 'Visual Arts Workshop',
		status: 'H',
		hours: 1,
		number_of_musicians: 1,
		total_fee: 322,
		notes: 'Paying 2 hours for prep and clean up.',
		program_name: 'CLC',
	},
	{
		date: 'Thursday, Dec 11, 2025',
		location: 'CLC / Palliative Care / Vent Unit',
		start_time: '1:00 PM',
		end_time: '3:00 PM',
		artist_name: 'Larry Siegel & Simón Gómez Villegas & Hasan Bakr',
		event_type: 'Bedside + Group Sing',
		status: 'CC',
		hours: 5,
		number_of_musicians: 3,
		notes: 'Bedside first hour / Group sing second hour - Siegel + Simón (2 hours) / Bakr 1 hr',
		program_name: 'CLC',
	},
	{
		date: 'Thursday, December 18, 2025',
		location: 'CLC',
		start_time: '2:30 PM',
		end_time: '3:00 PM',
		artist_name: 'Simón Gomez Villegas',
		event_type: 'Bedside',
		status: 'C',
		program_name: 'CLC',
	},
	{
		date: 'Thursday, December 18, 2025',
		location: 'CLC',
		start_time: '2:00 PM',
		end_time: '3:00 PM',
		artist_name: 'Ligel Lambert',
		event_type: 'Visual Arts Workshop',
		status: 'H',
		hours: 1,
		number_of_musicians: 1,
		total_fee: 322,
		notes: 'Paying 2 hours for prep and clean up.',
		program_name: 'CLC',
	},
	{
		date: 'Tuesday, December 23, 2025',
		location: 'CLC',
		start_time: '2:00 PM',
		end_time: '3:00 PM',
		event_type: 'Participatory Concert',
		program_name: 'CLC',
	},
]

// Sheet 3: Moynihan Train Hall Events
const moynihanEvents: EventRow[] = [
	{
		date: 'Tuesday, Nov 4, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'Drift Winds',
		status: 'CD',
		number_of_musicians: 3,
		event_type: 'Performance',
		description: 'Drift Winds brings flutist Anjali Shinde, oboist Matthew Maroon, and bassoonist Marty Tung together with the simple goal of sharing meaningful music with as many people as possible.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Thursday, Nov 6, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		event_type: 'Performance',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Tuesday, Nov 11, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'Benjamin Sutin & Gabriel Schillinger-Hyman',
		status: 'CC',
		number_of_musicians: 2,
		event_type: 'Performance',
		description: 'Award Winning Jazz Violinist Benjamin Sutin brings his vibrant blend of jazz, Latin, classic pop, and more to Moynihan Train Hall alongside Pianist Gabriel Schillinger Hyman.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Thursday, Nov 13, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'FAB5!',
		status: 'CC',
		number_of_musicians: 5,
		event_type: 'Performance',
		description: 'Victoria Paterson leads Mostly Modern\'s hugely popular FAB5! She brings a rich diversity of musicians & styles with pop music on classical instruments.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Tuesday, Nov 18, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'Big Apple Quintet',
		status: 'CC',
		number_of_musicians: 5,
		event_type: 'Performance',
		description: 'Friends since the age of 10, Rachel Handman (violin) and Keve Wilson (oboe) lead the Big Apple Band, made up of Broadway\'s star musicians.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Wednesday, Nov 19, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'Arbor Duo',
		status: 'CC',
		number_of_musicians: 2,
		event_type: 'Performance',
		description: 'Arbor Duo, featuring soprano Marisa Karchin and classical guitarist Dr. Alberta Khoury, explores the essence of love through diverse musical voices.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Thursday, Nov 20, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'Trio Fadolin',
		status: 'CC',
		number_of_musicians: 3,
		event_type: 'Performance',
		description: 'Trio Fadolín performs an eclectic repertoire from around the world and across the ages.',
		website: 'https://trio.fadolin.com',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Monday, Nov 24, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'Caracas Trio',
		status: 'CD',
		number_of_musicians: 3,
		event_type: 'Performance',
		description: 'The Caracas Trio blends Afro-Venezuelan rhythms with jazz improvisation through a unique instrumentation.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Tuesday, Nov 25, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'Justin Rothberg Trio',
		status: 'CD',
		number_of_musicians: 3,
		event_type: 'Performance',
		description: 'Justin Rothberg\'s trio performs a fusion of funky jazz, borrowing from various styles like hip hop, reggae, folk, and Afro Cuban.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Wednesday, Nov 26, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'Pedro Giraudo Tango Quartet',
		status: 'CC',
		number_of_musicians: 4,
		event_type: 'Performance',
		description: 'Latin GRAMMY Award winner Pedro Giraudo and his Tango Quartet trace the evolution of Argentine tango.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Tuesday, Dec 2, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'Big Apple Quintet',
		status: 'CC',
		number_of_musicians: 5,
		event_type: 'Performance',
		description: 'Friends since the age of 10, Rachel Handman (violin) and Keve Wilson (oboe) lead the Big Apple Band.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Wednesday, Dec 3, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		status: 'H',
		event_type: 'Performance',
		notes: 'LAGUARDIA HOLD',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Thursday, Dec 4, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		status: 'H',
		event_type: 'Performance',
		notes: 'LAGUARDIA HOLD',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Tuesday, Dec 9, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'Pedro Giraudo Tango Quartet',
		status: 'CC',
		number_of_musicians: 4,
		event_type: 'Performance',
		description: 'Latin GRAMMY Award winner Pedro Giraudo and his Tango Quartet.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Wednesday, Dec 10, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		status: 'H',
		event_type: 'Performance',
		notes: 'LAGUARDIA HOLD',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Thursday, Dec 11, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'Amir Farid',
		status: 'CC',
		number_of_musicians: 1,
		event_type: 'Performance',
		description: 'Pianist Amir Farid shares a wide range of music, from beloved classical works to contemporary pieces.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Saturday, Dec 13, 2025',
		location: 'Moynihan Train Hall',
		start_time: '3:00 PM',
		end_time: '5:00 PM',
		artist_name: 'FAB5',
		status: 'CD',
		number_of_musicians: 5,
		event_type: 'Performance',
		description: 'Victoria Paterson leads Mostly Modern\'s hugely popular FAB5! Holiday program.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Tuesday, Dec 16, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'Trio Fadolin',
		status: 'CC',
		number_of_musicians: 3,
		event_type: 'Performance',
		description: 'Trio Fadolín performs an eclectic repertoire.',
		website: 'https://trio.fadolin.com',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Wednesday, Dec 17, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'Sing for Hope HandaHarmony Youth Chorus',
		status: 'C',
		number_of_musicians: 25,
		event_type: 'Performance',
		description: 'The Sing for Hope HandaHarmony Youth Chorus presents holiday music from around the world.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Thursday, Dec 18, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'Klazz-Ma-Tazz plays Hard Bop Hanukkah',
		status: 'C',
		number_of_musicians: 4,
		event_type: 'Performance',
		description: 'Founded in 2014 by Benjamin Sutin, Klazz-Ma-Tazz explores Jewish, Eastern European and middle eastern music.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Saturday, Dec 20, 2025',
		location: 'Moynihan Train Hall',
		start_time: '3:00 PM',
		end_time: '5:00 PM',
		status: 'H',
		event_type: 'Performance',
		notes: 'LAGUARDIA HOLD',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Tuesday, Dec 23, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'Big Apple Quintet',
		status: 'CD',
		number_of_musicians: 5,
		event_type: 'Performance',
		description: 'Friends since the age of 10, Rachel Handman (violin) and Keve Wilson (oboe) lead the Big Apple Band.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Saturday, Dec 27, 2025',
		location: 'Moynihan Train Hall',
		start_time: '3:00 PM',
		end_time: '5:00 PM',
		artist_name: 'Simón Gomez Villegas',
		status: 'H',
		number_of_musicians: 1,
		event_type: 'Performance',
		description: 'Simón Gómez Villegas (they/all) is a captivating performer and composer hailing from Bogotá, Colombia.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Sunday, Dec 28, 2025',
		location: 'Moynihan Train Hall',
		start_time: '3:00 PM',
		end_time: '5:00 PM',
		artist_name: 'Sing Harlem',
		status: 'CS',
		number_of_musicians: 13,
		event_type: 'Performance',
		description: 'Sing for Hope presents Sing Harlem, the breakout musical group from the Mama Foundation for the Arts.',
		program_name: 'Moynihan Train Hall',
	},
	{
		date: 'Tuesday, Dec 30, 2025',
		location: 'Moynihan Train Hall',
		start_time: '4:00 PM',
		end_time: '6:00 PM',
		artist_name: 'Adam Narimatsu',
		status: 'C',
		number_of_musicians: 1,
		event_type: 'Performance',
		description: 'Adam Narimatsu is an NYC pianist with roots in New Orleans blues, stride, and jazz.',
		program_name: 'Moynihan Train Hall',
	},
]

// Combine all events
const allEvents = [...mskEvents, ...clcEvents, ...moynihanEvents]

console.log('\n' + '='.repeat(70))
console.log('EVENT IMPORT - USER PROVIDED DATA')
console.log('='.repeat(70))
console.log(`Mode: ${dryRun ? 'DRY RUN (no data will be saved)' : 'LIVE (data WILL be saved)'}`)
console.log(`Total events to import: ${allEvents.length}`)
console.log(`  - MSK Hospital: ${mskEvents.length} events`)
console.log(`  - CLC: ${clcEvents.length} events`)
console.log(`  - Moynihan Train Hall: ${moynihanEvents.length} events`)
console.log('='.repeat(70) + '\n')

if (!dryRun) {
	console.log('⚠️  WARNING: This is a LIVE import. Data will be written to the database.')
	console.log('⚠️  Run with --dry-run flag first to preview the import.\n')
}

importEvents(allEvents, dryRun)
	.then(() => {
		console.log('\n✅ Import process complete!')
		process.exit(0)
	})
	.catch((error) => {
		console.error('\n❌ Import failed:', error)
		process.exit(1)
	})
