<script lang="ts">
	import { onMount } from 'svelte'
	import { Calendar, Plus, X } from 'lucide-svelte'
	
	interface ScheduleBlock {
		id: string
		time: string
		duration: number // minutes
		activity: string
		notes?: string
		artist_id?: string // For artist-specific blocks
		artist_name?: string // For display
		is_auto_generated?: boolean // True if auto-generated from artist assignment
	}
	
	interface Props {
		schedule?: any // Can be JSON object, array, or string
		onUpdate?: (schedule: ScheduleBlock[]) => void
		readonly?: boolean
		event?: {
			start_time?: string | null
			end_time?: string | null
			artists?: {
				assignments?: Array<{
					artist_id: string
					artist_name?: string
					role?: string
				}>
			}
		}
	}
	
	let { schedule, onUpdate, readonly = false, event }: Props = $props()
	
	// Component state
	let scheduleBlocks = $state<ScheduleBlock[]>([])
	let showAddForm = $state(false)
	let editingIndex = $state<number | null>(null)
	let editingBlockEndTime = $state('')
	let jsonEditMode = $state(false)
	let jsonString = $state('')
	let viewMode = $state<'calendar' | 'list'>('calendar')
	
	// New block form
	let newBlock = $state<ScheduleBlock>({
		id: '',
		time: '',
		duration: 60,
		activity: '',
		notes: '',
		artist_id: '',
		artist_name: ''
	})
	
	// End time for the new block (calculated or entered directly)
	let newBlockEndTime = $state('')
	let isCustomActivity = $state(false)
	
	// Available artists for extra blocks
	let availableArtists = $derived(() => {
		if (!event?.artists?.assignments) return []
		return event.artists.assignments.map(a => ({
			id: a.artist_id,
			name: a.artist_name || 'Unknown Artist'
		}))
	})
	
	// Activity templates
	const activityTemplates = [
		{ name: 'Sound Check', duration: 30 },
		{ name: 'Rehearsal', duration: 60 },
		{ name: 'Performance', duration: 45 },
		{ name: 'Setup', duration: 30 },
		{ name: 'Break', duration: 15 },
		{ name: 'Meet & Greet', duration: 20 },
		{ name: 'Photo Session', duration: 15 },
		{ name: 'Cleanup', duration: 30 }
	]
	
	// Parse initial schedule on mount
	onMount(() => {
		initializeSchedule()
	})
	
	// Watch for changes in schedule prop and event
	$effect(() => {
		initializeSchedule()
	})
	
	function initializeSchedule() {
		// First, try to parse existing schedule
		let existingBlocks: ScheduleBlock[] = []
		
		if (schedule) {
			try {
				let parsed: any
				
				if (typeof schedule === 'string') {
					if (schedule.trim().startsWith('{') || schedule.trim().startsWith('[')) {
						parsed = JSON.parse(schedule)
					} else {
						parsed = []
					}
				} else if (Array.isArray(schedule)) {
					parsed = schedule
				} else if (typeof schedule === 'object') {
					if (schedule.blocks) {
						parsed = schedule.blocks
					} else {
						parsed = []
					}
				}
				
				existingBlocks = (parsed || []).map((block: any, index: number) => ({
					id: block.id || `block-${index}`,
					time: block.time || '',
					duration: Number(block.duration) || 60,
					activity: block.activity || block.name || String(block),
					notes: block.notes || '',
					artist_id: block.artist_id,
					artist_name: block.artist_name,
					is_auto_generated: block.is_auto_generated || false
				}))
			} catch (error) {
				console.error('Failed to parse schedule:', error)
				existingBlocks = []
			}
		}
		
		// Auto-generate blocks from artists if we have event times and artists
		const autoGeneratedBlocks: ScheduleBlock[] = []
		
		if (event?.start_time && event?.end_time && event?.artists?.assignments) {
			const startTime = event.start_time
			const endTime = event.end_time
			const duration = calculateDurationMinutes(startTime, endTime)
			
			// Check which artists already have blocks
			const artistsWithBlocks = new Set(
				existingBlocks
					.filter(b => b.artist_id && b.is_auto_generated)
					.map(b => b.artist_id)
			)
			
			// Create blocks for artists that don't have auto-generated blocks yet
			for (const assignment of event.artists.assignments) {
				if (!artistsWithBlocks.has(assignment.artist_id)) {
					autoGeneratedBlocks.push({
						id: `auto-${assignment.artist_id}-${Date.now()}`,
						time: startTime,
						duration: duration,
						activity: 'Performance',
						notes: assignment.role ? `Role: ${assignment.role}` : '',
						artist_id: assignment.artist_id,
						artist_name: assignment.artist_name,
						is_auto_generated: true
					})
				}
			}
		}
		
		// Merge existing blocks with auto-generated ones
		// Keep existing blocks that aren't auto-generated, or update auto-generated ones
		const mergedBlocks: ScheduleBlock[] = []
		const processedArtistIds = new Set<string>()
		
		// First, add all non-auto-generated blocks
		for (const block of existingBlocks) {
			if (!block.is_auto_generated) {
				mergedBlocks.push(block)
			} else if (block.artist_id) {
				processedArtistIds.add(block.artist_id)
				// Update existing auto-generated block with current event times
				if (event?.start_time && event?.end_time) {
					const duration = calculateDurationMinutes(event.start_time, event.end_time)
					mergedBlocks.push({
						...block,
						time: event.start_time,
						duration: duration
					})
				} else {
					mergedBlocks.push(block)
				}
			}
		}
		
		// Then add new auto-generated blocks for artists that don't have them
		for (const block of autoGeneratedBlocks) {
			if (block.artist_id && !processedArtistIds.has(block.artist_id)) {
				mergedBlocks.push(block)
			}
		}
		
		scheduleBlocks = mergedBlocks
		updateJsonString()
		onUpdate?.(scheduleBlocks)
	}
	
	function calculateDurationMinutes(startTime: string, endTime: string): number {
		try {
			const [startHours, startMins] = startTime.split(':').map(Number)
			const [endHours, endMins] = endTime.split(':').map(Number)
			const startTotal = startHours * 60 + startMins
			const endTotal = endHours * 60 + endMins
			return endTotal - startTotal
		} catch {
			return 60
		}
	}
	
	function updateJsonString() {
		jsonString = JSON.stringify(scheduleBlocks, null, 2)
	}
	
	function addBlock() {
		if (!newBlock.activity.trim()) return
		if (!newBlock.time) return
		
		// Calculate duration from end time if provided, otherwise use duration field
		let finalDuration = newBlock.duration
		if (newBlockEndTime && newBlock.time) {
			finalDuration = calculateDurationMinutes(newBlock.time, newBlockEndTime)
			if (finalDuration <= 0) {
				// Invalid time range, use duration field instead
				finalDuration = newBlock.duration
			}
		}
		
		const block: ScheduleBlock = {
			...newBlock,
			id: `block-${Date.now()}`,
			activity: newBlock.activity.trim(),
			duration: finalDuration,
			is_auto_generated: false
		}
		
		scheduleBlocks.push(block)
		onUpdate?.(scheduleBlocks)
		updateJsonString()
		
		// Reset form
		newBlock = {
			id: '',
			time: '',
			duration: 60,
			activity: '',
			notes: '',
			artist_id: '',
			artist_name: ''
		}
		newBlockEndTime = ''
		isCustomActivity = false
		showAddForm = false
	}
	
	function removeBlock(index: number) {
		scheduleBlocks.splice(index, 1)
		onUpdate?.(scheduleBlocks)
		updateJsonString()
	}
	
	function moveBlock(index: number, direction: 'up' | 'down') {
		const newIndex = direction === 'up' ? index - 1 : index + 1
		if (newIndex < 0 || newIndex >= scheduleBlocks.length) return
		
		const temp = scheduleBlocks[index]
		scheduleBlocks[index] = scheduleBlocks[newIndex]
		scheduleBlocks[newIndex] = temp
		
		onUpdate?.(scheduleBlocks)
		updateJsonString()
	}
	
	function startEdit(index: number) {
		editingIndex = index
		const block = scheduleBlocks[index]
		if (block.time && block.duration) {
			editingBlockEndTime = calculateEndTime(block.time, block.duration)
		} else {
			editingBlockEndTime = ''
		}
	}
	
	function cancelEdit() {
		editingIndex = null
		editingBlockEndTime = ''
		parseSchedule() // Reset any unsaved changes
	}
	
	function saveEdit(index: number) {
		const block = scheduleBlocks[index]
		// Update duration from end time if provided
		if (block.time && editingBlockEndTime) {
			const newDuration = calculateDurationMinutes(block.time, editingBlockEndTime)
			if (newDuration > 0) {
				block.duration = newDuration
			}
		}
		onUpdate?.(scheduleBlocks)
		updateJsonString()
		editingIndex = null
		editingBlockEndTime = ''
	}
	
	function useTemplate(template: { name: string; duration: number }) {
		newBlock.activity = template.name
		newBlock.duration = template.duration
		// Calculate end time from start time and duration
		if (newBlock.time) {
			newBlockEndTime = calculateEndTime(newBlock.time, template.duration)
		}
	}
	
	// Update end time when start time or duration changes
	$effect(() => {
		if (newBlock.time && newBlock.duration && !newBlockEndTime) {
			newBlockEndTime = calculateEndTime(newBlock.time, newBlock.duration)
		}
	})
	
	// Update duration when end time changes
	$effect(() => {
		if (newBlock.time && newBlockEndTime) {
			const calculatedDuration = calculateDurationMinutes(newBlock.time, newBlockEndTime)
			if (calculatedDuration > 0) {
				newBlock.duration = calculatedDuration
			}
		}
	})
	
	function toggleJsonMode() {
		if (jsonEditMode) {
			// Save JSON changes
			try {
				const parsed = JSON.parse(jsonString)
				scheduleBlocks = parsed
				onUpdate?.(scheduleBlocks)
			} catch (error) {
				console.error('Invalid JSON:', error)
				// Don't switch modes if JSON is invalid
				return
			}
		} else {
			updateJsonString()
		}
		jsonEditMode = !jsonEditMode
	}
	
	function calculateEndTime(startTime: string, duration: number): string {
		if (!startTime) return ''
		
		try {
			const [hours, minutes] = startTime.split(':').map(Number)
			const totalMinutes = hours * 60 + minutes + duration
			const endHours = Math.floor(totalMinutes / 60) % 24
			const endMins = totalMinutes % 60
			
			return `${endHours.toString().padStart(2, '0')}:${endMins.toString().padStart(2, '0')}`
		} catch {
			return ''
		}
	}
	
	function getTotalDuration(): number {
		return scheduleBlocks.reduce((total, block) => total + block.duration, 0)
	}
	
	function formatDuration(minutes: number): string {
		const hours = Math.floor(minutes / 60)
		const mins = minutes % 60
		if (hours > 0) {
			return `${hours}h ${mins}m`
		}
		return `${mins}m`
	}
	
	// Calendar view helpers
	function getTimeSlots() {
		const slots: string[] = []
		for (let hour = 0; hour < 24; hour++) {
			for (let minute = 0; minute < 60; minute += 30) {
				slots.push(`${hour.toString().padStart(2, '0')}:${minute.toString().padStart(2, '0')}`)
			}
		}
		return slots
	}
	
	function getBlocksForTimeSlot(timeSlot: string): ScheduleBlock[] {
		return scheduleBlocks.filter(block => {
			if (!block.time) return false
			const [blockHour, blockMin] = block.time.split(':').map(Number)
			const [slotHour, slotMin] = timeSlot.split(':').map(Number)
			const blockStart = blockHour * 60 + blockMin
			const blockEnd = blockStart + block.duration
			const slotStart = slotHour * 60 + slotMin
			const slotEnd = slotStart + 30
			return blockStart < slotEnd && blockEnd > slotStart
		})
	}
	
	function getBlockPosition(block: ScheduleBlock, hourRow: number): { top: number; height: number } {
		if (!block.time) return { top: 0, height: 0 }
		
		const [blockHours, blockMinutes] = block.time.split(':').map(Number)
		const startMinutes = blockHours * 60 + blockMinutes
		const rowStartMinutes = hourRow * 60
		const rowEndMinutes = (hourRow + 1) * 60
		
		// Calculate position relative to the hour row (0-100%)
		const minutesIntoRow = Math.max(0, startMinutes - rowStartMinutes)
		const top = (minutesIntoRow / 60) * 100 // Percentage within the hour
		const height = Math.min(100, (block.duration / 60) * 100) // Percentage based on duration, capped at 100%
		
		return { top, height }
	}
	
	function getBlockForHour(block: ScheduleBlock, hour: number): boolean {
		if (!block.time) return false
		const [blockHour] = block.time.split(':').map(Number)
		const duration = block.duration || 60
		const blockEndHour = blockHour + Math.ceil(duration / 60)
		return blockHour === hour || (blockHour < hour && blockEndHour > hour)
	}
	
	function formatTime(time: string): string {
		if (!time) return ''
		const [hours, minutes] = time.split(':')
		const hour = parseInt(hours)
		const ampm = hour >= 12 ? 'PM' : 'AM'
		const displayHour = hour % 12 || 12
		return `${displayHour}:${minutes} ${ampm}`
	}
	
	// Get visible time range based on blocks
	function getVisibleTimeRange(): { start: number; end: number } {
		if (scheduleBlocks.length === 0) {
			return { start: 8, end: 20 } // Default 8 AM to 8 PM
		}
		
		let minHour = 24
		let maxHour = 0
		
		for (const block of scheduleBlocks) {
			if (block.time) {
				const [hours] = block.time.split(':').map(Number)
				const endHour = hours + Math.ceil(block.duration / 60)
				minHour = Math.min(minHour, hours)
				maxHour = Math.max(maxHour, endHour)
			}
		}
		
		return {
			start: Math.max(0, minHour - 1),
			end: Math.min(24, maxHour + 1)
		}
	}
	
	function addExtraBlockForArtist(artistId: string, artistName: string) {
		if (!event?.start_time) return
		
		// Calculate time 1 hour before event start
		const [hours, minutes] = event.start_time.split(':').map(Number)
		const prepTime = new Date()
		prepTime.setHours(hours - 1, minutes, 0, 0)
		const prepTimeStr = `${prepTime.getHours().toString().padStart(2, '0')}:${prepTime.getMinutes().toString().padStart(2, '0')}`
		
		newBlock = {
			id: '',
			time: prepTimeStr,
			duration: 60,
			activity: 'Prep',
			notes: '',
			artist_id: artistId,
			artist_name: artistName
		}
		showAddForm = true
	}
</script>

<div class="space-y-4">
	<!-- Header -->
	<div class="flex items-center justify-between">
		<div>
			<h4 class="text-lg font-semibold">Event Schedule</h4>
			<p class="text-sm opacity-60">
				Total duration: {formatDuration(getTotalDuration())}
			</p>
		</div>
		{#if !readonly}
			<div class="flex gap-2">
				<button 
					class="btn btn-outline btn-sm"
					onclick={toggleJsonMode}
				>
					{jsonEditMode ? 'Visual Editor' : 'JSON Editor'}
				</button>
				{#if !jsonEditMode}
					<button 
						class="btn btn-primary btn-sm"
						onclick={() => showAddForm = !showAddForm}
					>
						{showAddForm ? 'Cancel' : 'Add Block'}
					</button>
				{/if}
			</div>
		{/if}
	</div>

	{#if jsonEditMode}
		<!-- JSON Editor -->
		<div class="card bg-base-200">
			<div class="card-body p-4">
				<h5 class="card-title text-base">JSON Schedule Editor</h5>
				<textarea
					bind:value={jsonString}
					class="textarea textarea-bordered font-mono text-sm"
					rows="15"
					placeholder="Enter schedule as JSON..."
					readonly={readonly}
				></textarea>
				{#if !readonly}
					<div class="flex justify-end gap-2 mt-2">
						<button 
							class="btn btn-outline btn-sm"
							onclick={() => jsonEditMode = false}
						>
							Cancel
						</button>
						<button 
							class="btn btn-primary btn-sm"
							onclick={toggleJsonMode}
						>
							Apply Changes
						</button>
					</div>
				{/if}
			</div>
		</div>
	{:else}
		<!-- View Mode Toggle -->
		<div class="flex items-center justify-end gap-2 mb-4">
			<div class="btn-group">
				<button
					class="btn btn-sm {viewMode === 'calendar' ? 'btn-active' : 'btn-outline'}"
					onclick={() => viewMode = 'calendar'}
				>
					Calendar View
				</button>
				<button
					class="btn btn-sm {viewMode === 'list' ? 'btn-active' : 'btn-outline'}"
					onclick={() => viewMode = 'list'}
				>
					List View
				</button>
			</div>
		</div>

		{#if viewMode === 'calendar'}
			{@const timeRange = getVisibleTimeRange()}
			{@const hours = Array.from({ length: timeRange.end - timeRange.start }, (_, i) => timeRange.start + i)}
			<!-- Calendar View -->
			<div class="card bg-base-100 border">
				<div class="card-body p-4">
					<div class="relative">
						<div class="space-y-1">
							{#each hours as hour}
								<div class="flex items-start gap-2 min-h-[60px] border-b border-base-200">
									<!-- Time label -->
									<div class="w-20 text-right text-xs text-base-content/60 pt-1">
										{formatTime(`${hour.toString().padStart(2, '0')}:00`)}
									</div>
									
									<!-- Blocks container -->
									<div class="flex-1 relative min-h-[60px]">
										{#each scheduleBlocks.filter(block => getBlockForHour(block, hour)) as block}
											{@const position = getBlockPosition(block, hour)}
											{@const isOverlapping = scheduleBlocks.filter(b => {
												if (!b.time || !block.time) return false
												const [bHour, bMin] = b.time.split(':').map(Number)
												const [blockHour, blockMin] = block.time.split(':').map(Number)
												const bStart = bHour * 60 + bMin
												const bEnd = bStart + (b.duration || 60)
												const blockStart = blockHour * 60 + blockMin
												const blockEnd = blockStart + (block.duration || 60)
												return b.id !== block.id && bStart < blockEnd && bEnd > blockStart
											}).length > 0}
											
											<div
												class="absolute left-0 right-0 rounded px-2 py-1 text-xs text-white shadow-sm border border-white/20 {block.is_auto_generated ? 'bg-primary' : 'bg-secondary'} {isOverlapping ? 'z-10' : 'z-0'}"
												style="top: {position.top}%; height: {position.height}%; min-height: 24px;"
												title="{block.artist_name || block.activity} - {formatTime(block.time)} ({formatDuration(block.duration)})"
											>
												<div class="font-semibold truncate">{block.artist_name || block.activity}</div>
												<div class="text-[10px] opacity-90 truncate">
													{formatTime(block.time)} - {calculateEndTime(block.time, block.duration)}
												</div>
												{#if block.notes}
													<div class="text-[10px] opacity-75 truncate mt-0.5">{block.notes}</div>
												{/if}
												{#if !readonly}
													<button
														class="absolute top-0 right-0 w-4 h-4 bg-black/20 hover:bg-black/40 rounded-full flex items-center justify-center text-[10px]"
														onclick={(e) => {
															e.stopPropagation()
															removeBlock(scheduleBlocks.indexOf(block))
														}}
														title="Remove"
													>
														×
													</button>
												{/if}
											</div>
										{/each}
									</div>
								</div>
							{/each}
						</div>
					</div>
					
					<!-- Artist quick actions -->
					{#if availableArtists.length > 0 && !readonly}
						<div class="mt-4 pt-4 border-t border-base-200">
							<div class="text-sm font-semibold mb-2">Add Extra Time for Artist:</div>
							<div class="flex flex-wrap gap-2">
								{#each availableArtists as artist}
									<button
										class="btn btn-xs btn-outline"
										onclick={() => addExtraBlockForArtist(artist.id, artist.name)}
									>
										<Plus class="w-3 h-3 mr-1" />
										{artist.name} (+1hr prep)
									</button>
								{/each}
							</div>
						</div>
					{/if}
				</div>
			</div>
		{:else}
			<!-- List View -->
		
			<!-- Add Block Form -->
			{#if showAddForm && !readonly}
				<div class="card bg-base-200 border">
					<div class="card-body p-4">
						<h5 class="card-title text-base">Add Schedule Block</h5>
						
						<!-- Templates -->
						<div class="mb-4">
							<label class="label">
								<span class="label-text">Quick Templates</span>
							</label>
							<div class="flex flex-wrap gap-2">
								{#each activityTemplates as template}
									<button
										type="button"
										class="btn btn-xs btn-outline"
										onclick={() => useTemplate(template)}
									>
										{template.name} ({template.duration}m)
									</button>
								{/each}
							</div>
						</div>
						
						<div class="grid grid-cols-1 md:grid-cols-3 gap-4">
							<!-- Artist (optional) -->
							{#if availableArtists.length > 0}
								<div>
									<label class="label">
										<span class="label-text">Artist (optional)</span>
									</label>
									<select
										bind:value={newBlock.artist_id}
										class="select select-bordered w-full"
										onchange={(e) => {
											const selected = availableArtists.find(a => a.id === e.target.value)
											if (selected) {
												newBlock.artist_name = selected.name
											}
										}}
									>
										<option value="">None</option>
										{#each availableArtists as artist}
											<option value={artist.id}>{artist.name}</option>
										{/each}
									</select>
								</div>
							{/if}
							
							<!-- Start Time -->
							<div>
								<label class="label">
									<span class="label-text">Start Time *</span>
								</label>
								<input
									type="time"
									bind:value={newBlock.time}
									class="input input-bordered w-full"
									required
								/>
							</div>
							
							<!-- End Time -->
							<div>
								<label class="label">
									<span class="label-text">End Time *</span>
								</label>
								<input
									type="time"
									bind:value={newBlockEndTime}
									class="input input-bordered w-full"
									required
								/>
								{#if newBlock.time && newBlockEndTime}
									<div class="text-xs opacity-60 mt-1">
										Duration: {formatDuration(calculateDurationMinutes(newBlock.time, newBlockEndTime))}
									</div>
								{/if}
							</div>
							
							<!-- Duration (alternative input, hidden but kept for backwards compatibility) -->
							<div class="hidden">
								<input
									type="number"
									bind:value={newBlock.duration}
									min="1"
									step="5"
								/>
							</div>
							
							<!-- Activity -->
							<div>
								<label class="label">
									<span class="label-text">Activity *</span>
								</label>
								{#if !isCustomActivity}
									<select
										class="select select-bordered w-full"
										onchange={(e) => {
											const value = e.target.value
											if (value === 'Other') {
												isCustomActivity = true
												newBlock.activity = ''
											} else if (value) {
												newBlock.activity = value
												// Set duration from template if available
												const template = activityTemplates.find(t => t.name === value)
												if (template && newBlock.time) {
													newBlock.duration = template.duration
													newBlockEndTime = calculateEndTime(newBlock.time, template.duration)
												}
											}
										}}
									>
										<option value="">Select activity</option>
										{#each activityTemplates as template}
											<option value={template.name}>{template.name}</option>
										{/each}
										<option value="Other">Other (custom)</option>
									</select>
								{/if}
								{#if isCustomActivity}
									<div class="flex gap-2">
										<input
											type="text"
											bind:value={newBlock.activity}
											class="input input-bordered w-full"
											placeholder="Enter custom activity name"
											required
										/>
										<button
											type="button"
											class="btn btn-outline btn-sm"
											onclick={() => {
												isCustomActivity = false
												newBlock.activity = ''
											}}
											title="Use template instead"
										>
											×
										</button>
									</div>
								{/if}
							</div>
							
							<!-- Notes -->
							<div class="md:col-span-3">
								<label class="label">
									<span class="label-text">Notes</span>
								</label>
								<textarea
									bind:value={newBlock.notes}
									class="textarea textarea-bordered w-full"
									rows="2"
									placeholder="Additional notes for this schedule block..."
								></textarea>
							</div>
						</div>
						
						<!-- Form Actions -->
						<div class="flex justify-end gap-2 mt-4">
							<button 
								class="btn btn-outline btn-sm"
								onclick={() => showAddForm = false}
							>
								Cancel
							</button>
							<button 
								class="btn btn-primary btn-sm"
								onclick={addBlock}
								disabled={!newBlock.activity.trim() || !newBlock.time || !newBlockEndTime}
							>
								Add Block
							</button>
						</div>
					</div>
				</div>
			{/if}

			<!-- Schedule Blocks List -->
			{#if scheduleBlocks.length > 0}
				<div class="space-y-2">
					{#each scheduleBlocks as block, index}
						<div class="card bg-base-100 border {block.is_auto_generated ? 'border-primary/30' : ''}">
							<div class="card-body p-4">
								<div class="flex items-start justify-between">
									<div class="flex-1">
										{#if editingIndex === index}
											<!-- Edit Mode -->
											<div class="grid grid-cols-1 md:grid-cols-3 gap-4">
												<div>
													<label class="label">
														<span class="label-text">Start Time</span>
													</label>
													<input
														type="time"
														bind:value={block.time}
														class="input input-bordered input-sm w-full"
														onchange={() => {
															if (block.time && editingBlockEndTime) {
																block.duration = calculateDurationMinutes(block.time, editingBlockEndTime)
															}
														}}
													/>
												</div>
												<div>
													<label class="label">
														<span class="label-text">End Time</span>
													</label>
													<input
														type="time"
														bind:value={editingBlockEndTime}
														class="input input-bordered input-sm w-full"
														onchange={() => {
															if (block.time && editingBlockEndTime) {
																block.duration = calculateDurationMinutes(block.time, editingBlockEndTime)
															}
														}}
													/>
													{#if block.time && editingBlockEndTime}
														<div class="text-xs opacity-60 mt-1">
															Duration: {formatDuration(calculateDurationMinutes(block.time, editingBlockEndTime))}
														</div>
													{/if}
												</div>
												<div>
													<label class="label">
														<span class="label-text">Activity</span>
													</label>
													<input
														type="text"
														bind:value={block.activity}
														class="input input-bordered input-sm w-full"
														placeholder="Enter activity name"
													/>
												</div>
												<div class="md:col-span-3">
													<label class="label">
														<span class="label-text">Notes</span>
													</label>
													<textarea
														bind:value={block.notes}
														class="textarea textarea-bordered textarea-sm w-full"
														rows="2"
													></textarea>
												</div>
											</div>
										{:else}
											<!-- View Mode -->
											<div class="flex items-center gap-4 flex-wrap">
												{#if block.is_auto_generated}
													<div class="badge badge-primary badge-sm">Auto</div>
												{/if}
												{#if block.artist_name}
													<div class="badge badge-outline">{block.artist_name}</div>
												{/if}
												{#if block.time}
													<div class="text-sm font-mono bg-base-200 px-2 py-1 rounded">
														{block.time} - {calculateEndTime(block.time, block.duration)}
													</div>
												{/if}
												<div class="badge badge-outline">
													{formatDuration(block.duration)}
												</div>
												<div class="font-medium">{block.activity}</div>
											</div>
											{#if block.notes}
												<p class="text-sm opacity-70 mt-2">{block.notes}</p>
											{/if}
										{/if}
									</div>
									
									{#if !readonly}
										<div class="flex items-center gap-1 ml-4">
											{#if editingIndex === index}
												<button 
													class="btn btn-xs btn-success"
													onclick={() => saveEdit(index)}
												>
													Save
												</button>
												<button 
													class="btn btn-xs btn-outline"
													onclick={cancelEdit}
												>
													Cancel
												</button>
											{:else}
												<button 
													class="btn btn-xs btn-outline"
													onclick={() => moveBlock(index, 'up')}
													disabled={index === 0}
												>
													↑
												</button>
												<button 
													class="btn btn-xs btn-outline"
													onclick={() => moveBlock(index, 'down')}
													disabled={index === scheduleBlocks.length - 1}
												>
													↓
												</button>
												<button 
													class="btn btn-xs btn-outline"
													onclick={() => startEdit(index)}
												>
													Edit
												</button>
												<button 
													class="btn btn-xs btn-error"
													onclick={() => removeBlock(index)}
												>
													×
												</button>
											{/if}
										</div>
									{/if}
								</div>
							</div>
						</div>
					{/each}
				</div>
			{:else}
				<div class="text-center py-8 bg-base-200 rounded-lg">
					<Calendar class="w-16 h-16 mx-auto text-base-content/70" />
					<p class="mt-2 text-lg">No schedule blocks</p>
					<p class="text-sm opacity-60">
						{readonly ? 'No schedule defined for this event' : 'Click "Add Block" to create a schedule'}
					</p>
				</div>
			{/if}
		{/if}
	{/if}
</div>